spring.application.name=eureka-server

server.port=8761

# Eureka server config
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation (optional for dev)
eureka.server.enable-self-preservation=false
