# ===============================
# SERVER CONFIG
# ===============================
server.port=8761
spring.application.name=DISCOVERY-SERVICE

# ===============================
# EUREKA ? NE PAS S'AUTO-ENREGISTRER
# ===============================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# ===============================
# LOGGING
# ===============================
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
logging.pattern.console=%d{HH:mm:ss} %-5level [EUREKA] %msg%n